// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('logoutUser', function($http) {
    return function() {
      return $http.post('http://localhost:3000/logout');
    };
  });

  app.factory('loginUser', function($http) {
    return function(user) {
      return $http.post('http://localhost:3000/login', user);
    };
  });

  app.factory('signupUser', function($http) {
    return function(user) {
      return $http.post('http://localhost:3000/registry', user);
    };
  });

}).call(this);

//# sourceMappingURL=authUser.js.map
