// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('postComment', function($http) {
    return function(comment) {
      return $http.post('http://localhost:3000/comment/save', comment);
    };
  });

  app.factory('getComments', function($http) {
    return function(id) {
      return $http.post('http://localhost:3000/comment/all', {
        id: id
      });
    };
  });

  app.factory('likeComment', function($http) {
    return function(id) {
      return $http.post('http://localhost:3000/comment/like', {
        id: id
      });
    };
  });

}).call(this);

//# sourceMappingURL=forComment.js.map
