// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('getHighRateFactory', [
    '$http', function($http) {
      return {
        get: function() {
          return $http.get('http://localhost:3000/ratedarticles');
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=getHighRate.js.map
