// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('getTags', function($http) {
    return $http.get('http://localhost:3000/tags').then(function(data) {
      return data.data;
    });
  });

}).call(this);

//# sourceMappingURL=getTags.js.map
