// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('getUserData', function($http) {
    return function(id) {
      if (id) {
        return $http.get('http://localhost:3000/user/' + id);
      } else {
        return $http.get('http://localhost:3000/currentUser');
      }
    };
  });

  app.factory('avatarFactory', function($http) {
    return function(data) {
      return $http.post('http://localhost:3000/avatar', data);
    };
  });

}).call(this);

//# sourceMappingURL=getUserData.js.map
