// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('avatarCtrl', [
    '$scope', 'PhotoLoader', function($scope, PhotoLoader) {
      $scope.imageStrings = [];
      $scope.processFiles = function(files) {
        angular.forEach(files, function(flowFile, i) {
          var fileReader;
          fileReader = new FileReader;
          fileReader.readAsDataURL(flowFile.file);
          fileReader.onload = function(event) {
            var uri;
            uri = event.target.result;
            $scope.imageStrings[i] = uri;
            PhotoLoader({
              img: uri
            });
            console.log(uri);
          };
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=avatar_controller.js.map
