// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('changeCtrl', [
    '$scope', 'translationService', '$css', function($scope, translationService, $css) {
      this.translate = function() {
        translationService.getTranslation($scope, this.selectedLanguage);
      };
      console.log(this.selectedLanguage);
      this.selectedLanguage = 'en';
      this.translate();
      this.selectedTheme = 'light';
      this.switchTheme = function() {
        if (this.selectedTheme === 'light') {
          $css.add('../source/assets/css/style.css');
          $css.remove('../source/assets/css/style2.css');
        } else {
          $css.remove('../source/assets/css/style.css');
          $css.add('../source/assets/css/style2.css');
        }
        return;
        return this.switchTheme();
      };
    }
  ]);

  app.service('translationService', function($resource) {
    this.getTranslation = function($scope, language) {
      var languageFilePath;
      languageFilePath = '../app/controllers/translation_' + language + '.json';
      console.log(languageFilePath);
      $resource(languageFilePath).get(function(data) {
        console.log(data);
        $scope.translation = data;
      });
    };
  });

}).call(this);

//# sourceMappingURL=change_controller.js.map
