// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('changeCtrl', [
    '$scope', '$css', 'TranslationService', "changeFactory", function($scope, $css, TranslationService, changeFactory) {
      this.translate = function() {
        if (this.selectedLanguage === 'ru') {
          this.selectedLanguage = 'en';
        } else {
          this.selectedLanguage = 'ru';
        }
        changeFactory({
          theme: this.selectedTheme,
          language: this.selectedLanguage
        });
        TranslationService.switchLanguage(this.selectedLanguage);
        $scope.translation = TranslationService.translation;
      };
      this.selectedLanguage = 'ru';
      this.translate();
      this.selectedTheme = 'light';
      this.switchTheme = function() {
        if (this.selectedTheme === 'light') {
          this.selectedTheme = 'dark';
        } else {
          this.selectedTheme = 'light';
        }
        changeFactory({
          theme: this.selectedTheme,
          language: this.selectedLanguage
        });
        if (this.selectedTheme === 'light') {
          $css.add('../source/assets/css/style.css');
          $css.remove('../source/assets/css/style2.css');
        } else {
          $css.remove('../source/assets/css/style.css');
          $css.add('../source/assets/css/style2.css');
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=change_controller.js.map
