// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('changeCtrl', [
    '$scope', '$css', 'TranslationService', 'changeFactory', 'getUser', function($scope, $css, TranslationService, changeFactory, getUser) {
      var switchLanguage, switchTheme;
      switchLanguage = function() {
        TranslationService.switchLanguage($scope.selectedLanguage);
        $scope.translation = TranslationService.translation;
      };
      switchTheme = function() {
        if ($scope.selectedTheme === 'light') {
          $css.add('../source/assets/css/style.css');
          $css.remove('../source/assets/css/style2.css');
        } else {
          $css.remove('../source/assets/css/style.css');
          $css.add('../source/assets/css/style2.css');
        }
      };
      $scope.translate = function() {
        if ($scope.selectedLanguage === 'ru') {
          $scope.selectedLanguage = 'en';
        } else {
          $scope.selectedLanguage = 'ru';
        }
        changeFactory({
          theme: $scope.selectedTheme,
          language: $scope.selectedLanguage
        });
        switchLanguage();
      };
      $scope.switchTheme = function() {
        if ($scope.selectedTheme === 'light') {
          $scope.selectedTheme = 'dark';
        } else {
          $scope.selectedTheme = 'light';
        }
        changeFactory({
          theme: $scope.selectedTheme,
          language: $scope.selectedLanguage
        });
        switchTheme();
      };
      $scope.selectedLanguage = 'en';
      $scope.selectedTheme = 'light';
      switchLanguage();
      switchTheme();
      getUser().then(function(data) {
        $scope.user = data.data;
        $scope.selectedLanguage = $scope.user.language;
        $scope.selectedTheme = $scope.user.theme;
        switchLanguage();
        switchTheme();
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=change_controller.js.map
