// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('viewComments', [
    '$scope', 'getComments', 'likeComment', function($scope, getComments, likeComment) {
      $scope.commentsPromise = $scope.postPromise.then(function() {
        return getComments($scope.post.id).then(function(comments) {
          $scope.reviews = comments.data;
        });
      });
      $scope.like = function(review) {
        if (!review.likeable) {
          return;
        }
        review.likes += 1;
        review.likeable = false;
        likeComment(review.id).then(function() {
          return console.log('LIKE NEBEDA');
        }, function() {
          console.log('LIKE BEDA');
        });
      };
    }
  ]);

  app.controller('addComments', [
    '$scope', 'getUserData', 'postComment', function($scope, getUserData, postComment) {
      getUserData().then(function(data) {
        $scope.user = data.data;
        $scope.createNewReview = function() {
          $scope.viewComment = {
            author: $scope.user,
            id: $scope.post.id
          };
        };
        $scope.postPromise.then(function() {
          return $scope.createNewReview();
        });
        return $scope.addReview = function() {
          postComment($scope.viewComment).then(function(comment) {
            $scope.reviews.push(comment.data);
            $scope.createNewReview();
          }, function() {
            return console.log("BEDA");
          });
        };
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=comments.js.map
