// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('contentCtrl', [
    '$scope', 'PostService', 'ImageService', function($scope, PostService, ImageService) {
      var changeSettings;
      $scope.showSettings = false;
      $scope.showInfo = true;
      $scope.showPost = false;
      $scope.changeSettings = function() {
        $scope.showSettings = true;
        return $scope.showInfo = false;
      };
      $scope.saveSettings = function() {
        $scope.showSettings = false;
        $scope.showInfo = true;
      };
      $scope.templatePanel = false;
      $scope.firstPost = false;
      $scope.secondPost = false;
      $scope.thirdPost = false;
      $scope.template = 'photo';
      $scope.createPost = function() {
        $scope.templatePanel = true;
        $scope.firstPost = true;
        return $scope.showPost = true;
      };
      $scope.addPost = function() {
        $scope.templatePanel = false;
        $scope.showPost = false;
        changeSettings(false, false, false, $scope.template);
        $scope.templateAction();
        return changeSettings(false, false, false, $scope.template);
      };
      $scope.videoUrl = '';
      $scope.templateAction = function() {
        $scope.templateData.template = $scope.template;
        PostService.saveNewPost($scope.templateData);
      };
      $scope.showFirstTemplate = function() {
        changeSettings(true, false, false, 'photo');
      };
      $scope.showSecondTemplate = function() {
        changeSettings(false, true, false, 'video');
      };
      $scope.showThirdTemplate = function() {
        changeSettings(false, false, true, 'map');
      };
      $scope.setData = function(data) {
        $scope.templateData = data;
      };
      changeSettings = function(first, second, third, template) {
        $scope.firstPost = first;
        $scope.secondPost = second;
        $scope.thirdPost = third;
        $scope.template = template;
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=content_controller.js.map
