// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('contentCtrl', [
    '$scope', 'PostService', function($scope, PostService) {
      var changeSettings;
      $scope.showSettings = false;
      $scope.showInfo = true;
      $scope.showPost = false;
      $scope.changeSettings = function() {
        $scope.showSettings = true;
        return $scope.showInfo = false;
      };
      $scope.saveSettings = function() {
        $scope.showSettings = false;
        $scope.showInfo = true;
      };
      $scope.templatePanel = false;
      $scope.firstPost = false;
      $scope.secondPost = false;
      $scope.thirdPost = false;
      $scope.createPost = function() {
        $scope.templatePanel = true;
        $scope.firstPost = true;
        return $scope.showPost = true;
      };
      $scope.addPost = function() {
        $scope.templatePanel = false;
        $scope.showPost = false;
        changeSettings(false, false, false, $scope.template);
        return $scope.templateAction();
      };
      $scope.templateAction = function() {
        PostService.saveNewPost($scope.templateData());
      };
      $scope.showFirstTemplate = function() {
        changeSettings(true, false, false);
      };
      $scope.showSecondTemplate = function() {
        changeSettings(false, true, false);
      };
      $scope.showThirdTemplate = function() {
        changeSettings(false, false, true);
      };
      $scope.setData = function(data) {
        $scope.templateData = data;
      };
      $scope.removePost = function(post) {
        return PostService.deletePost(post.id).then(function(result) {
          var idx;
          if (result) {
            idx = $scope.posts.indexOf(post);
            if (idx > -1) {
              return $scope.posts.splice(idx, 1);
            }
          }
        });
      };
      changeSettings = function(first, second, third) {
        $scope.firstPost = first;
        $scope.secondPost = second;
        $scope.thirdPost = third;
      };
      $scope.setCategory = function(category) {
        $scope.category = category;
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=content_controller.js.map
