// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('dataOfUser', [
    '$scope', 'getUserData', 'updateFactory', function($scope, getUserData, updateFactory) {
      $scope.user = null;
      getUserData().then(function(data) {
        return $scope.user = data.data;
      });
      $scope.saveUserSettings = function() {
        var post;
        $scope.saveSettings();
        post = {
          firstName: $scope.user.firstName,
          lastName: $scope.user.lastName,
          about: $scope.user.about
        };
        return updateFactory(post);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=dataOfUser.js.map
