// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('ImageListController', function($scope, ImageService) {
    $scope.images = ImageService.imagelist;
    $scope.image = ImageService.image;
    $scope.remove = function() {
      ImageService.imagelist[0] = [];
    };
  });

}).call(this);

//# sourceMappingURL=image_list_controller.js.map
