// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('ImageList', function($scope, ImageService) {
    $scope.images = ImageService.imagelist;
    $scope.image = ImageService.image;
    $scope.remove = function() {
      ImageService.imagelist[0] = [];
    };
    $scope.selected = void 0;
  });

}).call(this);

//# sourceMappingURL=imageList.js.map
