// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('langFactory', function(translation_en, translation_ru) {
    var dictionary;
    dictionary = {
      'en': translation_en,
      'ru': translation_ru
    };
    return function(lang) {
      return dictionary[lang];
    };
  });

}).call(this);

//# sourceMappingURL=langFactory.js.map
