// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('loginCtrl', [
    '$scope', 'UserData', function($scope) {
      UserData.success(function(data) {
        $scope.user = data;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=login_controller.js.map
