// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('mainCtrl', [
    '$scope', '$routeParams', 'getUser', 'getPosts', 'sendRating', 'getHighRate', 'TranslationService', function($scope, $routeParams, getUser, getPosts, sendRating, getHighRate) {
      var destinations;
      destinations = {
        'user': getPosts($scope.user),
        'all': getHighRate
      };
      $scope.destination = $routeParams.destination;
      $scope.posts = [];
      $scope.predicate = 'score';
      $scope.user = 0;
      getUser().then(function(data) {
        return $scope.user = data;
      });
      $scope.action = function() {
        destinations[$scope.destination].get().then(function(posts) {
          $scope.posts = posts.data;
        }, function(err) {
          console.log(err.data);
        });
      };
      $scope.action();
      $scope.changeRating = function(post, inc) {
        var rating;
        rating = {
          id: post.id,
          score: inc
        };
        console.log(rating);
        sendRating(rating).success(function(res) {
          console.log(res);
          post.score = res.score;
        }).error(function() {
          return console.log("already rated");
        });
      };
      $scope.order = function(predicate) {
        return $scope.predicate = predicate;
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=main_page_controller.js.map
