// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.filter('byTag', function() {
    return function(items, tag) {
      var currentTags, i, item, len, result;
      result = [];
      if (!tag || tag === '') {
        return items;
      } else {
        for (i = 0, len = items.length; i < len; i++) {
          item = items[i];
          currentTags = item.tags.map(function(tag) {
            return tag.name;
          });
          if (currentTags.indexOf(tag) !== -1) {
            result.push(item);
          }
        }
      }
      return result;
    };
  });

  app.filter('byCategory', function() {
    return function(items_, category) {
      var i, item, len, result;
      result = [];
      if (!category || category === '') {
        return items_;
      } else {
        for (i = 0, len = items_.length; i < len; i++) {
          item = items_[i];
          if (item.category === category) {
            result.push(item);
          }
        }
      }
      return result;
    };
  });

  app.controller('mainController', [
    '$scope', '$routeParams', 'getUserData', 'getPosts', 'rateCreative', 'getHighRateFactory', 'SearchService', function($scope, $routeParams, getUserData, getPosts, rateCreative, getHighRateFactory, SearchService) {
      var userId;
      $scope.destination = $routeParams.destination;
      $scope.posts = [];
      $scope.predicate = 'score';
      $scope.user = null;
      userId = $scope.destination === 'id' ? $routeParams.param : null;
      getUserData(userId).then(function(data) {
        return $scope.user = data.data;
      }).then(function() {
        return $scope.checkPosts();
      }, function() {
        return $scope.checkPosts();
      });
      $scope.action = function() {
        $scope.destinations[$scope.destination].get().then(function(posts) {
          posts.data.map(function(post) {
            return post.createdAt = Date.parse(post.createdAt);
          });
          $scope.posts = posts.data;
        });
      };
      $scope.changeRating = function(post, inc) {
        var rating;
        if (!post.ratable) {
          return;
        }
        post.ratable = false;
        rating = {
          id: post.id,
          score: inc
        };
        rateCreative(rating).success(function(res) {
          post.score = res.score;
        });
      };
      $scope.checkPosts = function() {
        if (SearchService.posts) {
          $scope.posts = SearchService.posts;
          SearchService.posts = null;
        } else {
          $scope.destinations = {
            'user': getPosts($scope.user ? $scope.user.id : 0),
            'all': getHighRateFactory,
            'id': getPosts($routeParams.param ? $routeParams.param : 999)
          };
          if ($routeParams.destination === 'tag') {
            $scope.filteringTag = $routeParams.param;
            $scope.destination = 'all';
          }
          if ($routeParams.destination === 'category') {
            $scope.filteringCategory = $routeParams.param;
            $scope.destination = 'all';
          }
          $scope.action();
        }
      };
      $scope.order = function(predicate) {
        return $scope.predicate = predicate;
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=mainPage.js.map
