// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('mapCtrl', function($scope, $window) {
    $scope.mapReady = function() {
      return $window.navigator.geolocation.getCurrentPosition(function(position) {
        var coords, latitude, longitude, map, mapOptions, marker;
        latitude = position.coords.latitude;
        longitude = position.coords.longitude;
        coords = new google.maps.LatLng(latitude, longitude);
        mapOptions = {
          zoom: 15,
          center: coords,
          mapTypeControl: true,
          navigationControlOptions: {
            style: google.maps.NavigationControlStyle.SMALL
          },
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
        marker = new google.maps.Marker({
          position: coords,
          map: map,
          title: 'Your current location!'
        });
      });
    };
  });

}).call(this);

//# sourceMappingURL=map_controller.js.map
