// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.config(function(uiGmapGoogleMapApiProvider) {
    uiGmapGoogleMapApiProvider.configure({
      v: '3',
      libraries: 'weather,geometry,visualization'
    });
  });

  app.controller('mapCtrl', [
    '$scope', '$window', 'uiGmapGoogleMapApi', 'PostService', 'ImageService', function($scope, $window, uiGmapGoogleMapApi, PostService, ImageService) {
      var dataFactory;
      $scope.mapCoordinates = {
        currentX: 0,
        currentY: 0,
        pointX: 0,
        pointY: 0
      };
      dataFactory = function() {
        var data, tags;
        tags = $scope.tags ? $scope.tags.split(" ") : [];
        return data = {
          category: $scope.category,
          title: $scope.title_,
          description: $scope.description_,
          article: $scope.article,
          tags: tags.map(function(tag) {
            return {
              name: tag
            };
          }),
          img: ImageService.imagelist[0] ? ImageService.imagelist[0].base64 : '',
          map: $scope.mapCoordinates,
          template: 'map'
        };
      };
      $scope.postMap = function() {
        $scope.setData(dataFactory);
        return $scope.addPost();
      };
      $window.navigator.geolocation.getCurrentPosition(function(position) {
        $scope.mapCoordinates.currentY = $scope.latitude = position.coords.latitude;
        return $scope.mapCoordinates.currentX = $scope.longitude = position.coords.longitude;
      });
      $scope.showMap = false;
      $scope.mapReady = function() {
        uiGmapGoogleMapApi.then(function() {
          $scope.showMap = true;
          $scope.map = {
            center: {
              latitude: $scope.latitude,
              longitude: $scope.longitude
            },
            zoom: 5,
            markers: [],
            events: {
              click: function(map, eventName, originalEventArgs) {
                var e, lat, lon, marker;
                e = originalEventArgs[0];
                $scope.mapCoordinates.pointY = lat = e.latLng.lat();
                $scope.mapCoordinates.pointX = lon = e.latLng.lng();
                marker = {
                  id: Date.now(),
                  coords: {
                    latitude: lat,
                    longitude: lon
                  }
                };
                $scope.map.markers[0] = marker;
                $scope.$apply();
              }
            }
          };
          $scope.options = {
            scrollwheel: false
          };
          return $scope.marker = {
            id: 0,
            coords: {
              latitude: $scope.latitude,
              longitude: $scope.longitude
            },
            options: {
              icon: '../../source/assets/img/blue_marker.png'
            }
          };
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=map_controller.js.map
