// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('mapViewCtrl', [
    '$scope', 'uiGmapGoogleMapApi', function($scope, uiGmapGoogleMapApi) {
      uiGmapGoogleMapApi.then(function() {
        $scope.map = {
          center: {
            latitude: 60,
            longitude: 60
          },
          zoom: 5
        };
        $scope.options = {
          scrollwheel: false
        };
        $scope.marker2 = {
          id: 1,
          coords: {
            latitude: 65,
            longitude: 65
          }
        };
        return $scope.marker = {
          id: 0,
          coords: {
            latitude: 60,
            longitude: 60
          },
          options: {
            icon: '../../source/assets/img/blue_marker.png'
          }
        };
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=map_view_controller.js.map
