// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('mapViewCtrl', [
    '$scope', '$routeParams', 'getPost', 'uiGmapGoogleMapApi', function($scope, $routeParams, getPost, uiGmapGoogleMapApi) {
      var mapFunction;
      getPost($routeParams.postId).get().success(function(post) {
        $scope.post = post;
        if (post.map) {
          return mapFunction(post.map);
        }
      });
      mapFunction = function(markerCoords) {
        return uiGmapGoogleMapApi.then(function() {
          $scope.map = {
            center: {
              latitude: markerCoords[1],
              longitude: markerCoords[0]
            },
            zoom: 4
          };
          $scope.marker2 = {
            id: 1,
            coords: {
              latitude: markerCoords[3],
              longitude: markerCoords[2]
            }
          };
          return $scope.marker = {
            id: 0,
            coords: {
              latitude: markerCoords[1],
              longitude: markerCoords[0]
            },
            options: {
              icon: '../../source/assets/img/blue_marker.png'
            }
          };
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=map_view_controller.js.map
