// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('NavBarController', [
    '$scope', 'logoutUser', 'SearchService', 'getUser', function($scope, logoutUser, SearchService, getUser) {
      $scope.logout = function() {
        return logoutUser().then(function() {
          window.location.href = 'http://localhost:8000/app/#/';
        });
      };
      $scope.user = null;
      getUser().then(function(data) {
        return $scope.user = data;
      });
      $scope.searchText = "";
      $scope.searching = function() {
        SearchService.loadResults($scope.searchText).then(function(data) {
          console.log(data);
          $scope.searchText = '';
          window.location.href = 'http://localhost:8000/app/#/';
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=navbar_controller.js.map
