// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('NavBarController', [
    '$http', '$scope', 'UserDataService', function($http, $scope, UserDataService) {
      $scope.action = function() {
        return $http.post('http://localhost:3000/logout').then(function() {
          console.log(UserDataService.user);
          UserDataService.user = null;
          window.location.href = 'http://localhost:8000/app/#/';
        });
      };
      $scope.user = UserDataService.user;
    }
  ]);

}).call(this);

//# sourceMappingURL=navbar_controller.js.map
