// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('NavBarController', [
    '$scope', 'UserDataService', 'logoutUser', function($scope, UserDataService, logoutUser) {
      $scope.logout = function() {
        return logoutUser().then(function() {
          console.log(UserDataService.user);
          UserDataService.user = null;
          window.location.href = 'http://localhost:8000/app/#/';
        });
      };
      $scope.user = UserDataService.user;
    }
  ]);

}).call(this);

//# sourceMappingURL=navbar_controller.js.map
