// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('navigationPanel', [
    '$scope', 'logoutUser', 'SearchService', 'getUserData', function($scope, logoutUser, SearchService, getUserData) {
      $scope.logout = function() {
        return logoutUser().then(function() {
          window.location.href = 'http://localhost:8000/app/#/';
        });
      };
      $scope.user = null;
      getUserData().then(function(data) {
        return $scope.user = data;
      });
      $scope.searchText = "";
      $scope.searching = function() {
        SearchService.loadResults($scope.searchText).then(function(data) {
          $scope.searchText = '';
          SearchService.posts = data;
          window.location.href = 'http://localhost:8000/app/#/';
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=navigationPanel.js.map
