// Generated by CoffeeScript 1.10.0
(function() {
  var app, ctor;

  app = angular.module('myApp');

  ctor = function($scope, ImageService, PostService) {
    var action;
    action = function() {
      var tags;
      tags = $scope.tags.split(" ");
      return PostService.saveNewPost({
        title: $scope.title,
        description: $scope.description,
        article: $scope.article,
        tags: tags.map(function(tag) {
          return {
            name: tag
          };
        }),
        template: 'photo',
        img: ImageService.imagelist[0] ? ImageService.imagelist[0].base64 : '',
        map: PostService.mapCoordinates
      });
    };
    $scope.setAction(action);
  };

  app.controller('PhotoTemplateCtrl', ['$scope', 'ImageService', 'PostService', ctor]);

}).call(this);

//# sourceMappingURL=photo_template_controller.js.map
