// Generated by CoffeeScript 1.10.0
(function() {
  var app, ctor;

  app = angular.module('myApp');

  ctor = function($http, $scope, $routeParams, UserDataService) {
    var action;
    action = function() {
      var tags;
      console.log("Child Scope");
      tags = $scope.tags.split(" ");
      return $http.post('http://localhost:3000/registry', {
        title: $scope.title,
        description: $scope.description,
        article: $scope.article,
        tags: tags
      });
    };
    $scope.setAction(action);
  };

  app.controller('PhotoTemplateCtrl', ['$http', '$scope', '$routeParams', 'UserDataService', ctor]);

}).call(this);

//# sourceMappingURL=photo_template_controller.js.map
