// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('registrationCtrl', function($scope, userInfo) {
    $scope.userInfo = userInfo;
  });

}).call(this);

//# sourceMappingURL=registration_page_controller.js.map
