// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('RegistrationCtrl', [
    '$scope', '$routeParams', 'UserDataService', 'signupUser', 'loginUser', function($scope, $routeParams, UserDataService, signupUser, loginUser) {
      $scope.about = '';
      $scope.action = $routeParams.action;
      $scope.actions = {
        'signup': function() {
          return signupUser({
            email: $scope.email,
            password: $scope.password,
            username: $scope.name,
            surname: $scope.surname,
            about: $scope.about
          });
        },
        'login': function() {
          return loginUser({
            email: $scope.email,
            password: $scope.password
          });
        }
      };
      $scope.performAction = function() {
        return $scope.actions[$scope.action]().success(function(data) {
          UserDataService.user = data;
          window.location.href = 'http://localhost:8000/app/#/';
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=registration_controller.js.map
