// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('RegistrationCtrl', function($http, $scope) {
    $scope.about = '';
    $scope.submit = function() {
      return $http.post('http://local.host:3000/registry', {
        email: $scope.email,
        password: $scope.password,
        username: $scope.name,
        surname: $scope.surname,
        about: $scope.about
      });
    };
  });

}).call(this);

//# sourceMappingURL=RegistrationCtrl.js.map
