// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('tagCtrl', [
    '$scope', 'Tags', function($scope, Tags) {
      Tags.success(function(data) {
        var i;
        $scope.tagList = [];
        $scope.popList = [];
        i = 0;
        while (i < 15) {
          $scope.tagList.push(data(i)['name']);
          $scope.popList.push(data(i)['size']);
          i++;
        }
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=tag_controller.js.map
