// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('TemplateCtrl', [
    '$http', '$scope', '$routeParams', 'UserDataService', function($http, $scope, $routeParams, UserDataService) {
      $scope.actionPrototype = {};
    }
  ]);

}).call(this);

//# sourceMappingURL=template_controller.js.map
