// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp', ['angular-jqcloud']);

  app.controller('tagCtrl', function($scope) {
    $scope.words = ["test", "something", "next", "laugh"];
  });

}).call(this);

//# sourceMappingURL=test.js.map
