// Generated by CoffeeScript 1.10.0
(function() {
  myApp.controller('pageCtrl', function($scope, $css) {
    $css.add('../source/assets/css/bootstrap2.min.css');
    $css.remove('../source/assets/css/bootstrap.min.css');
    $css.remove('../source/assets/css/bootstrap2.min.css');
    $css.add('../source/assets/css/bootstrap.min.css');
  });

}).call(this);

//# sourceMappingURL=theme_controller.js.map
