// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('translationCtrl', [
    '$scope', 'translationService', function($scope, translationService) {
      this.translate = function() {
        translationService.getTranslation($scope, this.selectedLanguage);
      };
      console.log(this.selectedLanguage);
      this.selectedLanguage = 'en';
      this.translate();
    }
  ]);

  app.service('translationService', function($resource) {
    this.getTranslation = function($scope, language) {
      var languageFilePath;
      languageFilePath = '../app/controllers/translation_' + language + '.json';
      console.log(languageFilePath);
      $resource(languageFilePath).get(function(data) {
        console.log(data);
        $scope.translation = data;
      });
    };
  });

}).call(this);

//# sourceMappingURL=translation_controller.js.map
