// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('userDataCtrl', [
    '$scope', 'UserData', function($scope, UserData) {
      UserData.success(function(data) {
        $scope.user = data;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=user_data_controller.js.map
