// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('userCtrl', function($scope) {
    var changeSettings;
    $scope.changeButton_text = translation.SETTINGS;
    $scope.showSettings = false;
    $scope.showInfo = true;
    $scope.showPost = false;
    $scope.changeSettings = function() {
      if ($scope.showSettings === false) {
        $scope.showSettings = true;
        $scope.showInfo = false;
        $scope.changeButton_text = translation.SAVE;
      } else {
        $scope.showSettings = false;
        $scope.showInfo = true;
        $scope.changeButton_text = translation.SETTINGS;
      }
    };
    $scope.createButton_text = translation.CREATE;
    $scope.templatePanel = false;
    $scope.firstPost = false;
    $scope.secondPost = false;
    $scope.thirdPost = false;
    $scope.createPost = function() {
      if ($scope.templatePanel === false) {
        $scope.templatePanel = true;
        $scope.firstPost = true;
        $scope.createButton_text = translation.ADD;
        $scope.showPost = true;
      } else {
        $scope.templatePanel = false;
        $scope.createButton_text = translation.CREATE;
        $scope.showPost = false;
        $scope.firstPost = false;
        $scope.secondPost = false;
        $scope.thirdPost = false;
        $scope.action().success(function() {
          console.log("nebeda");
        }).error(function() {
          return console.log("beda");
        });
        changeSettings(false, false, false);
      }
    };
    $scope.showFirstTemplate = function() {
      changeSettings(true, false, false);
    };
    $scope.showSecondTemplate = function() {
      changeSettings(false, true, false);
    };
    $scope.showThirdTemplate = function() {
      changeSettings(false, false, true);
    };
    $scope.action = {};
    $scope.setAction = function(action) {
      $scope.action = action;
    };
    changeSettings = function(first, second, third) {
      $scope.firstPost = first;
      $scope.secondPost = second;
      $scope.thirdPost = third;
    };
  });

}).call(this);

//# sourceMappingURL=user_page_controller.js.map
