// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('userDataCtrl', [
    '$scope', 'UserDataService', function($scope, UserDataService) {
      this.user = UserDataService.user;
    }
  ]);

}).call(this);

//# sourceMappingURL=user_data_controller.js.map
