// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('contentCtrl', function($scope) {
    var changeSettings;
    $scope.showSettings = false;
    $scope.showInfo = true;
    $scope.showPost = false;
    $scope.changeSettings = function() {
      $scope.showSettings = true;
      return $scope.showInfo = false;
    };
    $scope.saveSettings = function() {
      $scope.showSettings = false;
      $scope.showInfo = true;
    };
    $scope.templatePanel = false;
    $scope.firstPost = false;
    $scope.secondPost = false;
    $scope.thirdPost = false;
    $scope.createPost = function() {
      $scope.templatePanel = true;
      $scope.firstPost = true;
      return $scope.showPost = true;
    };
    $scope.addPost = function() {
      $scope.templatePanel = false;
      $scope.showPost = false;
      $scope.firstPost = false;
      $scope.secondPost = false;
      $scope.thirdPost = false;
      $scope.action().success(function() {
        console.log("nebeda");
      }).error(function() {
        return console.log("beda");
      });
      return changeSettings(false, false, false);
    };
    $scope.showFirstTemplate = function() {
      changeSettings(true, false, false);
    };
    $scope.showSecondTemplate = function() {
      changeSettings(false, true, false);
    };
    $scope.showThirdTemplate = function() {
      changeSettings(false, false, true);
    };
    $scope.action = {};
    $scope.setAction = function(action) {
      $scope.action = action;
    };
    changeSettings = function(first, second, third) {
      $scope.firstPost = first;
      $scope.secondPost = second;
      $scope.thirdPost = third;
    };
  });

}).call(this);

//# sourceMappingURL=user_page_controller.js.map
