// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.filter('trustAsResourceUrl', [
    '$sce', function($sce) {
      return function(val) {
        return $sce.trustAsResourceUrl(val);
      };
    }
  ]);

  app.controller('videoCtrl', function($scope) {
    $scope.embeddify = function(videoUrl) {
      return videoUrl.replace('watch?v=', 'embed/');
    };
  });

}).call(this);

//# sourceMappingURL=video_controller.js.map
