// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('viewTemplateController', [
    '$scope', '$routeParams', 'getPost', function($scope, $routeParams, getPost) {
      getPost($routeParams.postId).get().success(function(post) {
        return $scope.post = post;
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=view_controller.js.map
