// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.controller('viewTemplateController', [
    '$scope', '$routeParams', 'getPost', function($scope, $routeParams, getPost) {
      getPost($routeParams.postId).get().success(function(post) {
        $scope.post = post;
        return $scope.mapFunction();
      });
      $scope.setData = function(data) {
        return $scope.mapFunction = data;
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=view_controller.js.map
