// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('myApp', ['ngRoute', 'myApp.view1', 'myApp.view2', 'myApp.version']).controller('MyCtr', function($scope) {
    $scope.world = 'Nik';
  });

}).call(this);

//# sourceMappingURL=apl.js.map
