// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp', ['ngRoute', 'myApp.version', 'angular-jqcloud', 'ui.bootstrap', 'hc.marked', 'door3.css', 'uiGmapgoogle-maps', 'flow']);

  app.config(function($httpProvider) {
    $httpProvider.defaults.useXDomain = true;
    $httpProvider.defaults.withCredentials = true;
    delete $httpProvider.defaults.headers.common['X-Requested-With'];
  });

}).call(this);

//# sourceMappingURL=app.js.map
