// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module("myApp");

  app.constant("translation_ru", {
    "SEND": "Отправить",
    "COMMENTS_PLACEHOLDER": "Ваш комментарий",
    "COMMENTS": "Комментарии",
    "PASSWORD_PLACEHOLDER": "Пароль",
    "PASSWORD": "Пароль",
    "ABOUT_PLACEHOLDER": "Расскажите о себе",
    "ABOUT": "О Вас",
    "EMAIL_PLACEHOLDER": "Почта",
    "EMAIL": "Почта",
    "SURNAME_PLACEHOLDER": "Фамилия",
    "SURNAME": "Фамилия",
    "NAME_PLACEHOLDER": "Имя",
    "NAME": "Имя",
    "TAGS_CLOUD": "Облако тэгов:",
    "YOUTUBE_VIDEO": "Youtube видео",
    "TEMPLATES": "Выберите шаблон:",
    "TAGS": "Введите тэги",
    "ARTICLE_PLACEHOLDER": "Ваша статья",
    "ARTICLE": "Статья",
    "IMAGE": "Фото",
    "DESCRIPTION_PLACEHOLDER": "Краткое описание",
    "DESCRIPTION": "Описание",
    "TITLE_PLACEHOLDER": "Ваш заголовок",
    "TITLE": "Заголовок",
    "SEARCH": "Поиск...",
    "MAIN": "Главная",
    "SIGN_OUT": "Выйти",
    "SIGN_IN": "Войти",
    "SIGN_UP": "Регистрация",
    "HOME": "Личный кабинет",
    "RATE": "Рейтинг",
    "COLOR": "Цвет",
    "light": "День",
    "dark": "Ночь",
    "CREATE": "Создать",
    "SETTINGS": "Настройки",
    "SAVE": "Сохранить",
    "ADD": "Добавить",
    "SUBMIT": "Подтвердить",
    "CANCEL": "Отмена",
    "CATEGORY": "Категория:",
    "COMPUTER": "Компьютерные технологии",
    "LANGUAGE": "Языки",
    "WORLD": "Вокруг света",
    "BIOLOGY": "Биология",
    "PHOTO": "Фотография",
    "USERPUBLICATIONS": "Мои публикации"
  });

}).call(this);

//# sourceMappingURL=translation_ru.js.map
