// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('changeFactory', function($http) {
    return function(settings) {
      return $http.post('http://localhost:3000/updateuser', settings);
    };
  });

}).call(this);

//# sourceMappingURL=changeFactory.js.map
