// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('delPost', function($http) {
    return function(id) {
      return $http["delete"]('http://localhost:3000/post/' + id);
    };
  });

}).call(this);

//# sourceMappingURL=deletePost.js.map
