// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('PhotoLoader', function($http) {
    return function(data) {
      return $http.post('http://localhost:3000/avatar', data);
    };
  });

}).call(this);

//# sourceMappingURL=downloadPhotoFactory.js.map
