// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.directive('dropDirective', [
    'ImageService', function(ImageService) {
      return {
        restrict: 'AE',
        link: function(scope, elem) {
          elem.bind('dragenter', function(event) {
            elem.textContent = '';
            event.stopPropagation();
            event.preventDefault();
          });
          elem.bind('dragover', function(event) {
            event.stopPropagation();
            event.preventDefault();
          });
          elem.bind('drop', function(event) {
            var dt, f, files, i, reader;
            event.stopPropagation();
            event.preventDefault();
            console.log('what', event.dataTransfer);
            dt = event.dataTransfer || event.originalEvent && event.originalEvent.dataTransfer;
            files = event.target.files || dt && dt.files;
            i = 0;
            f = void 0;
            while (f = files[i]) {
              reader = new FileReader;
              reader.readAsArrayBuffer(f);
              reader.onload = (function(theFile) {
                return function(e) {
                  var newFile;
                  newFile = {
                    name: theFile.name,
                    type: theFile.type,
                    size: theFile.size,
                    lastModifiedDate: theFile.lastModifiedDate
                  };
                  ImageService.imagelist.push({
                    stats: newFile,
                    file: theFile,
                    URL: URL.createObjectURL(theFile)
                  });
                  scope.$apply();
                  console.log('Imagelist', ImageService.imagelist.length);
                };
              })(f);
              console.log('Processed', f);
              i++;
            }
            ImageService.file = files[files.length - 1];
          });
        }
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=dropDirective.js.map
