// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('getPosts', function($http) {
    return function(id) {
      return {
        get: function() {
          return $http.get('http://localhost:3000/posts/' + id);
        }
      };
    };
  });

  app.factory('getPost', function($http) {
    return function(id) {
      return {
        get: function() {
          return $http.get('http://localhost:3000/post/' + id);
        }
      };
    };
  });

}).call(this);

//# sourceMappingURL=getPosts.js.map
