// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('getPosts', function($http) {
    return function(authId) {
      return $http.get('http://localhost:3000/posts/' + authId);
    };
  });

}).call(this);

//# sourceMappingURL=getPosts.js.map
