// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('HighRate', [
    '$http', function($http) {
      return $http.get('http://local.host:3000/rate');
    }
  ]);

}).call(this);

//# sourceMappingURL=highRatePublications.js.map
