// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.directive('imageDirective', [
    'ImageService', function(ImageService) {
      return {
        restrict: 'AE',
        template: '<li>' + '<span>' + '<img ng-src="{{image.URL}}" ng-click="select(image)" />' + '<button ng-click="remove(image)" class="btn-default btn-xs">X</button>' + '</span>' + '</li>',
        link: function(scope, elem) {}
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=imageDirective.js.map
