// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.service('ImageService', function() {
    this.imagelist = [];
    this.file = {};
    this.image = {};
  });

}).call(this);

//# sourceMappingURL=imageService.js.map
