// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('loginUser', function($http) {
    return function(user) {
      return $http.post('http://localhost:3000/login', user);
    };
  });

}).call(this);

//# sourceMappingURL=loginUser.js.map
