// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('logoutUser', function($http) {
    return function() {
      console.log('LOGGING OUT');
      return $http.post('http://localhost:3000/logout');
    };
  });

}).call(this);

//# sourceMappingURL=logoutUser.js.map
