// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.config(function($routeProvider) {
    $routeProvider.when('/', {
      controller: 'mainCtrl',
      templateUrl: '../app/main.html'
    }).when('/registry', {
      controller: 'registrationCtrl',
      templateUrl: '../app/registration.html'
    }).when('/user', {
      controller: 'userCtrl',
      templateUrl: '../templates/user.html'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);

//# sourceMappingURL=MainRout.js.map
