// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('Tags', [
    '$http', function($http) {
      return $http.get('http://local.host:3000/tags');
    }
  ]);

}).call(this);

//# sourceMappingURL=popularTags.js.map
