// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.service('PostService', [
    'savePost', 'delPostFactory', function(savePost, delPostFactory) {
      this.saveNewPost = function(post) {
        return savePost(post).then(function(data) {
          return data.data;
        });
      };
      this.deletePost = function(post) {
        return delPost(post).then(function(data) {
          return data.data;
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=postService.js.map
