// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.factory('savePost', function($http) {
    return function(post) {
      return $http.post('http://localhost:3000/post/save', post);
    };
  });

}).call(this);

//# sourceMappingURL=savePost.js.map
