// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.service('SearchService', [
    'searchFactory', function(searchFactory) {
      this.posts = "hello";
      this.setPosts = function(posts) {
        return this.posts = posts;
      };
      this.getPosts = function() {
        return this.posts;
      };
      this.loadResults = function(text, posts) {
        if (posts == null) {
          posts = this.posts;
        }
        return searchFactory(text).then(function(data) {
          console.log('BEFORE', posts);
          posts = data.data;
          console.log('AFTER', posts);
          return data.data;
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=searchService.js.map
