// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.service('SearchService', [
    'searchFactory', function(searchFactory) {
      this.posts = null;
      this.loadResults = function(text) {
        return searchFactory(text).then(function(data) {
          return data.data;
        });
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=searchService.js.map
