// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module('myApp');

  app.service('UserDataService', function() {
    this.user = null;
  });

}).call(this);

//# sourceMappingURL=userData.js.map
